import { required } from '@vuelidate/validators'
import state from '../resources/state'
export const collection = 'classes'
export const params = {
  relationship: ['level', 'degree', 'major', 'field']
}

export const columns = [
  {
    name: 'class',
    required: true,
    label: 'Class',
    align: 'left',
    field: 'class',
    format: (val) => val,
    sortable: true
  },

  // Always give this columns as default
  {
    name: 'action',
    label: null,
    field: 'key'
  }
]

export const form = {
  level_id: null,
  degree_id: null,
  major_id: null,
  field_id: null,
  class: null
}
export const resetValue = {...form}
export const layout = [
  [
    {
      type: 'QSelect',
      col: 'col-2',
      name: 'level_id',
      label: 'Level',
      props: {
        options: [],
        'use-input': true,
        'emit-value': true,
        'map-options': true,
        'option-value': 'id',
        'option-label': 'level',
        'hide-selected': true,
        'fill-input': true
      },
      reference: 'levels',
      updateValues: [], // update values to be null on value changed
      params: ['degree_id'], // additional params on searching
      events: {}
    },
    {
      type: 'QSelect',
      col: 'col-2',
      name: 'degree_id',
      label: 'Degree',
      props: {
        options: [],
        'use-input': true,
        'emit-value': true,
        'map-options': true,
        'option-value': 'id',
        'option-label': 'title',
        'hide-selected': true,
        'fill-input': true
      },
      reference: 'degrees',
      updateValues: ['major_id', 'level_id', 'field_id'], // update values to be null on value changed
      events: {}
    },
    {
      type: 'QSelect',
      col: 'col-2',
      name: 'major_id',
      label: 'Major',
      props: {
        options: [],
        'use-input': true,
        'emit-value': true,
        'map-options': true,
        'option-value': 'id',
        'option-label': 'title',
        'hide-selected': true,
        'fill-input': true
      },
      reference: 'majors',
      updateValues: ['field_id'], // update values to be null on value changed
      params: ['degree_id'], // additional params on searching
      events: {}
    },
    {
      type: 'QSelect',
      col: 'col',
      name: 'field_id',
      label: 'Field',
      props: {
        options: [],
        'use-input': true,
        'emit-value': true,
        'map-options': true,
        'option-value': 'id',
        'option-label': 'title',
        'hide-selected': true,
        'fill-input': true
      },
      reference: 'fields',
      updateValues: [], // update values to be null on value changed
      params: ['major_id', 'degree_id'], // additional params on searching
      events: {}
    },
  ],
  [
    {
      type: 'QInput',
      col: 'col-4',
      name: 'class',
      label: 'Class',
      props: {
        type: 'text',
        maxlength: 1024,
        placeholder: 'ex: 12 SMA IPA',
        hint: '-- optional: generated by system'
      },
      events: {}
    },
  ]
]

export const validation = {
  level_id: { required },
  degree_id: { required },
  major_id: { },
  field_id: { },
  class: { }
}

export default function () {
  return {
    ...state(),
    // Collection name
    collection,
    params,
    // Datatable config
    columns,
    form,
    resetValue,
    layout,
    validation
  }
}
